services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-api
    command: npm run start:prod
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${MONGODB_URI}
      - PORT=${APP_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    depends_on:
      - mongodb
    networks:
      - monitoring 